### PR TITLE
no error for patterned-input configuration, but only one file found at running

### PR DESCRIPTION
**Pull request by ronnin**
error found in the case following:

build.gradle 
```groovy
plantUml {
    render input: 'src/main/diagrams/*.puml', output: "${project.buildDir}/diagrams", format: 'png'
}
```
but we've just created only ONE puml file in the src/main/diagrams directory.

error is "FileNotFound: src/main/diagrams/*.puml"

### CODE REVIEW

**Comment by codecholeric** [comment]
Thanks a lot for the PR :smiley: You're right, I actually had a patch lying around for this (because I ran into it when testing myself). I just didn't expect that this plugin would actually be used (I published it more for myself with a strong doubt that anyone else would be interested).
Can you check, if version 1.2.0 with my old patch already fixes your problem?
BTW, I'm not sure if the part `to.name.endsWith(".${format.fileSuffix}")` wouldn't break the explicit file name case? Because `fileSuffix` AFAIK already contains a leading `.` (yes, it's valid to be surprised about that I guess :wink:)

**Comment by codecholeric** [comment]
I've checked my last assumption and it turns out my test was pretty bad :wink: It just checked `puml.svg` exists, but actually since `to.name.endsWith(".${format.fileSuffix}")` doesn't match, the output is generated into a folder `puml.svg` and then called in turn `first.svg`.
I've improved the test now, to fail in this case :smiley:

**Comment by ronnin** [comment]
yes, version 1.2.0 fixes the problem. thank you.

BTW,  There is another annoying problem, that the Gradle Daemon process wasn't exited after successfully running the `plantUml` task, while it is exited after other tasks, like `build`, `publishToLocal`
> "/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/bin/java -XX:MaxMetaspaceSize=256m -XX:+HeapDumpOnOutOfMemoryError -Xmx512m -Dfile.encoding=UTF-8 -Duser.country=CN -Duser.language=zh -Duser.variant -cp /usr/local/Cellar/gradle/5.1.1/libexec/lib/gradle-launcher-5.1.1.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 5.1.1"

I did some research, went deep into the Class net.sourceforge.plantuml.SourceStringReader, and more. but I didn't find the cause.

**Comment by codecholeric** [comment]
Are you sure there is a difference? I've tried to reproduce this, but in my example project both `build` and `plantuml` behave the same. They start a new daemon and that keeps running afterwards, which is as intended as I believe (the daemon should be persistent between different runs to make subsequent runs faster, so if it would exit, nothing was gained).
If I run multiple executions of `plantuml` the same Gradle daemon is reused, which seems okay...
You can always run `./gradlew plantuml --no-daemon` if this behavior is undesirable for you.

**Pull request closed without merging**
